name: Deploy Terraform to Azure

on:
  push:
    branches:
    - main
  pull_request:
  
jobs:  
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      #ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      #ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      #ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      #ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      #ARM_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
      #ARM_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
      #ARM_CONTAINER_NAME: ${{ secrets.AZURE_CONTAINER_NAME }}
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-la
    defaults:
      run:
        shell: bash
  
    steps:
    # Checkout the repository to the GitHub Actions runner  

    - name: Install Azure CLI
      run: |
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash -s -- -v 2.0.79


    