name: Terraform

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Terraform
      uses: actions/setup-terraform@v1
      with:
        terraform_version: 1.3.0
    - name: Configure Azure credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy infrastructure
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.3.0
        tf_actions_working_dir: .
        tf_actions_subcommand: apply
        tf_actions_auto_approve: true
